#!/usr/bin/env python3
"""Analyze Motivation measurements for the PEACE IPDPS'26 paper.

The Motivation section contains several measurement-driven arguments:

1) Request-length distributions (handled by `plot_trace_distribution.py`).
2) FIFO head-of-line blocking: short queueing delay + throughput with vs without long requests.
3) Reservation underutilization: GPU idle rate + short queueing delay + throughput vs FIFO.
4) Priority starvation: long-request starvation rate.
5) Preemption pressure: total number of long-prefill preemptions (Table in the paper).

This script focuses on (2)–(5) by reading experiment outputs generated by
`run_workload_routed.py` and (optionally) `gpu_idle_monitor.py`.

All code and comments are English-only.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np


# Import paper model labels.
EXP_DIR = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(EXP_DIR))
from peace_defaults import PAPER_MODELS  # type: ignore


PERCENTILES = [1, 25, 50, 75, 99]


def _read_json(path: Path) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _read_records_jsonl(path: Path) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(json.loads(line))
    return out


def _get_short_queue_delay_percentiles(summary: Dict[str, Any]) -> List[float]:
    q = summary.get("short_queue_delay_s") or {}
    vals: List[float] = []
    for p in PERCENTILES:
        vals.append(float(q.get(f"p{p}", float("nan"))))
    return vals


def _safe_div_list(xs: List[float], denom: float) -> List[float]:
    if denom is None or not np.isfinite(denom) or denom <= 0:
        return [float("nan") for _ in xs]
    return [float(x) / float(denom) if np.isfinite(x) else float("nan") for x in xs]


def _plot_boxpairs(
    labels: List[str],
    left_data: List[List[float]],
    right_data: List[List[float]],
    left_label: str,
    right_label: str,
    ylabel: str,
    out_path: Path,
) -> None:
    """Plot paired boxplots (paper style: each box uses 5 percentile points)."""
    fig, ax = plt.subplots(figsize=(8, 3.5))

    positions_left = np.arange(len(labels)) * 2.0
    positions_right = positions_left + 0.6
    mid = (positions_left + positions_right) / 2

    ax.boxplot(
        left_data,
        positions=positions_left,
        widths=0.5,
        patch_artist=True,
        whis=[0, 100],
        boxprops=dict(linewidth=1.3),
        medianprops=dict(color="black", linewidth=1.0),
        whiskerprops=dict(linewidth=1.3),
        capprops=dict(linewidth=1.3),
        flierprops=dict(marker="o", markersize=3, linestyle="none"),
    )
    ax.boxplot(
        right_data,
        positions=positions_right,
        widths=0.5,
        patch_artist=True,
        whis=[0, 100],
        boxprops=dict(linewidth=1.3),
        medianprops=dict(color="black", linewidth=1.0),
        whiskerprops=dict(linewidth=1.3),
        capprops=dict(linewidth=1.3),
        flierprops=dict(marker="o", markersize=3, linestyle="none"),
    )

    ax.set_xticks(mid)
    ax.set_xticklabels(labels, rotation=11)
    ax.set_ylim(0, 1.0)
    ax.set_ylabel(ylabel)

    # Simple legend using colored squares.
    legend_handles = [
        plt.Line2D([], [], marker="s", linestyle="None", label=left_label, markersize=12),
        plt.Line2D([], [], marker="s", linestyle="None", label=right_label, markersize=12),
    ]
    ax.legend(handles=legend_handles, loc="upper center", bbox_to_anchor=(0.5, 1.25), ncol=2, frameon=False)

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)


def _plot_throughput_bars(
    labels: List[str],
    left_vals: List[float],
    right_vals: List[float],
    left_label: str,
    right_label: str,
    out_path: Path,
) -> None:
    fig, ax = plt.subplots(figsize=(8, 3.5))
    positions_left = np.arange(len(labels)) * 2.0
    positions_right = positions_left + 0.6
    mid = (positions_left + positions_right) / 2

    ax.bar(positions_left, left_vals, width=0.5, edgecolor="black", label=left_label)
    ax.bar(positions_right, right_vals, width=0.5, edgecolor="black", label=right_label)

    ax.set_xticks(mid)
    ax.set_xticklabels(labels, rotation=11)
    ax.set_ylabel("Throughput (RPS)")

    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.25), ncol=2, frameon=False)

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)


def _iter_paper_models(selected: Optional[List[str]]) -> List[Tuple[str, str]]:
    """Return [(model_key, display_name)] in paper order."""
    order = ["mistral7b", "phi3_14b", "yi34b", "llama31_70b"]
    keys = selected if selected else order
    out: List[Tuple[str, str]] = []
    for k in keys:
        if k not in PAPER_MODELS:
            raise SystemExit(f"Unknown model key: {k}. Valid: {sorted(PAPER_MODELS.keys())}")
        out.append((k, PAPER_MODELS[k].display_name))
    return out


def analyze_fifo(results_root: Path, out_dir: Path, models: Optional[List[str]]) -> None:
    """FIFO with vs without long requests (Motivation Fig q_delay_fifo + throughput_fifo)."""
    labels: List[str] = []
    data_wo: List[List[float]] = []
    data_w: List[List[float]] = []
    thr_wo: List[float] = []
    thr_w: List[float] = []

    for key, name in _iter_paper_models(models):
        s_wo = results_root / "fifo" / key / "without_long" / "summary.json"
        s_w = results_root / "fifo" / key / "with_long" / "summary.json"
        if not s_wo.exists() or not s_w.exists():
            print(f"[warn] Missing FIFO summaries for {key}: {s_wo} or {s_w}")
            continue

        wo = _read_json(s_wo)
        w = _read_json(s_w)

        q_wo = _get_short_queue_delay_percentiles(wo)
        q_w = _get_short_queue_delay_percentiles(w)
        denom = float(q_w[-1])  # normalize by p99 with long

        labels.append(name)
        data_wo.append(_safe_div_list(q_wo, denom))
        data_w.append(_safe_div_list(q_w, denom))
        thr_wo.append(float(wo.get("short_throughput_rps", float("nan"))))
        thr_w.append(float(w.get("short_throughput_rps", float("nan"))))

    if labels:
        _plot_boxpairs(
            labels=labels,
            left_data=data_wo,
            right_data=data_w,
            left_label="w/o long",
            right_label="w/ long",
            ylabel="Normalized\nqueueing delay",
            out_path=out_dir / "q_delay_fifo.pdf",
        )
        _plot_throughput_bars(
            labels=labels,
            left_vals=thr_wo,
            right_vals=thr_w,
            left_label="w/o long",
            right_label="w/ long",
            out_path=out_dir / "throughput_fifo.pdf",
        )
        print(f"Wrote: {out_dir / 'q_delay_fifo.pdf'}")
        print(f"Wrote: {out_dir / 'throughput_fifo.pdf'}")


def analyze_reservation(results_root: Path, out_dir: Path, models: Optional[List[str]]) -> None:
    """Reservation vs FIFO (Motivation Fig q_delay_resv + throughput_resv)."""
    labels: List[str] = []
    data_fifo: List[List[float]] = []
    data_resv: List[List[float]] = []
    thr_fifo: List[float] = []
    thr_resv: List[float] = []

    for key, name in _iter_paper_models(models):
        s_fifo = results_root / "reservation" / key / "fifo" / "summary.json"
        s_resv = results_root / "reservation" / key / "reservation" / "summary.json"
        if not s_fifo.exists() or not s_resv.exists():
            print(f"[warn] Missing Reservation summaries for {key}: {s_fifo} or {s_resv}")
            continue

        fifo = _read_json(s_fifo)
        resv = _read_json(s_resv)

        q_fifo = _get_short_queue_delay_percentiles(fifo)
        q_resv = _get_short_queue_delay_percentiles(resv)
        denom = float(q_resv[-1])  # normalize by p99 of reservation

        labels.append(name)
        data_fifo.append(_safe_div_list(q_fifo, denom))
        data_resv.append(_safe_div_list(q_resv, denom))
        thr_fifo.append(float(fifo.get("short_throughput_rps", float("nan"))))
        thr_resv.append(float(resv.get("short_throughput_rps", float("nan"))))

    if labels:
        _plot_boxpairs(
            labels=labels,
            left_data=data_fifo,
            right_data=data_resv,
            left_label="FIFO",
            right_label="Reservation",
            ylabel="Normalized\nqueueing delay",
            out_path=out_dir / "q_delay_resv.pdf",
        )
        _plot_throughput_bars(
            labels=labels,
            left_vals=thr_fifo,
            right_vals=thr_resv,
            left_label="FIFO",
            right_label="Reservation",
            out_path=out_dir / "throughput_resv.pdf",
        )
        print(f"Wrote: {out_dir / 'q_delay_resv.pdf'}")
        print(f"Wrote: {out_dir / 'throughput_resv.pdf'}")


def analyze_priority_starvation(results_root: Path, out_dir: Path, models: Optional[List[str]]) -> None:
    """Compute long-request starvation rate under Priority baseline."""
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: List[Dict[str, Any]] = []
    for key, name in _iter_paper_models(models):
        rec_path = results_root / "priority" / key / "records.jsonl"
        if not rec_path.exists():
            print(f"[warn] Missing Priority records for {key}: {rec_path}")
            continue

        recs = _read_records_jsonl(rec_path)
        long_recs = [r for r in recs if str(r.get("request_type", "")).lower() == "long"]
        total = len(long_recs)

        def _served(r: Dict[str, Any]) -> bool:
            if r.get("error"):
                return False
            # If http_status is absent, assume success if latency exists.
            hs = r.get("http_status")
            if hs is not None:
                try:
                    hs_i = int(hs)
                    if hs_i < 200 or hs_i >= 300:
                        return False
                except Exception:
                    return False
            return r.get("latency_s") is not None

        served = sum(1 for r in long_recs if _served(r))
        starved = total - served
        rate = (float(starved) / float(total)) if total > 0 else float("nan")

        rows.append(
            {
                "model_key": key,
                "model": name,
                "long_total": total,
                "long_served": served,
                "long_starved": starved,
                "starvation_rate": rate,
            }
        )

    csv_path = out_dir / "starvation_rate.csv"
    if rows:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
        print(f"Wrote: {csv_path}")


def _aggregate_idle_from_jsons(json_paths: List[Path]) -> Optional[float]:
    total_busy = 0.0
    total_idle = 0.0
    for p in json_paths:
        try:
            obj = _read_json(p)
        except Exception:
            continue
        total_busy += float(obj.get("total_busy_s", 0.0))
        total_idle += float(obj.get("total_idle_s", 0.0))

    denom = total_busy + total_idle
    if denom <= 0:
        return None
    return total_idle / denom


def analyze_gpu_idle(results_root: Path, out_dir: Path, models: Optional[List[str]]) -> None:
    """Aggregate GPU idle monitor outputs into a paper-style table."""
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: List[Dict[str, Any]] = []
    for key, name in _iter_paper_models(models):
        for method in ("fifo", "reservation"):
            base = results_root / "gpu_idle" / method / key
            if not base.exists():
                continue
            jsons = sorted(base.glob("*.json"))
            if not jsons:
                continue
            idle = _aggregate_idle_from_jsons(jsons)
            if idle is None:
                continue
            rows.append(
                {
                    "model_key": key,
                    "model": name,
                    "method": method,
                    "idle_rate": idle,
                    "num_files": len(jsons),
                }
            )

    csv_path = out_dir / "gpu_idle_rate.csv"
    if rows:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
        print(f"Wrote: {csv_path}")
    else:
        print("[warn] No GPU idle monitor files found; skipping.")


def analyze_preemptions(results_root: Path, out_dir: Path, models: Optional[List[str]], variant: str) -> None:
    """Extract total preemptions from summary.json (Table in Motivation section).

    Expected layout:
      results_root/preemptions/<model_key>/summary.json
    or:
      results_root/preemptions/<model_key>/<variant>/summary.json

    The paper's Motivation table corresponds to the total number of times long
    request prefill is preempted by short-prefill.

    In the provided experiment harness, this is recorded as:
      summary["long_preemptions_total"]

    (when the server emits per-request preemption counts in the stream).
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: List[Dict[str, Any]] = []
    for key, name in _iter_paper_models(models):
        p1 = results_root / "preemptions" / key / "summary.json"
        p2 = results_root / "preemptions" / key / variant / "summary.json"
        path = p1 if p1.exists() else p2 if p2.exists() else None
        if path is None:
            print(f"[warn] Missing preemption summary for {key}: {p1} or {p2}")
            continue

        s = _read_json(path)
        pre = s.get("long_preemptions_total")
        rows.append({"model_key": key, "model": name, "long_preemptions_total": pre})

    csv_path = out_dir / "preemptions_total.csv"
    if rows:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
        print(f"Wrote: {csv_path}")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Analyze PEACE Motivation measurement results.")
    sub = p.add_subparsers(dest="cmd", required=True)

    def _add_common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--results-root", type=str, required=True, help="Root directory containing results.")
        sp.add_argument("--out-dir", type=str, required=True, help="Directory to write plots/tables.")
        sp.add_argument(
            "--models",
            type=str,
            nargs="*",
            default=None,
            help="Optional subset of model keys (default: all paper models).",
        )

    sp_fifo = sub.add_parser("fifo", help="Analyze FIFO with vs without long requests.")
    _add_common(sp_fifo)

    sp_resv = sub.add_parser("reservation", help="Analyze Reservation vs FIFO.")
    _add_common(sp_resv)

    sp_pri = sub.add_parser("priority", help="Analyze Priority starvation rate.")
    _add_common(sp_pri)

    sp_idle = sub.add_parser("gpu-idle", help="Aggregate GPU idle monitor outputs.")
    _add_common(sp_idle)

    sp_pre = sub.add_parser("preemptions", help="Extract total preemptions table.")
    _add_common(sp_pre)
    sp_pre.add_argument("--variant", type=str, default="fsp", help="Optional subdir name for variant.")

    sp_all = sub.add_parser("all", help="Run all analyses.")
    _add_common(sp_all)
    sp_all.add_argument("--variant", type=str, default="fsp")

    return p.parse_args()


def main() -> int:
    args = parse_args()
    results_root = Path(args.results_root)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.cmd == "fifo":
        analyze_fifo(results_root, out_dir, args.models)
    elif args.cmd == "reservation":
        analyze_reservation(results_root, out_dir, args.models)
    elif args.cmd == "priority":
        analyze_priority_starvation(results_root, out_dir, args.models)
    elif args.cmd == "gpu-idle":
        analyze_gpu_idle(results_root, out_dir, args.models)
    elif args.cmd == "preemptions":
        analyze_preemptions(results_root, out_dir, args.models, args.variant)
    elif args.cmd == "all":
        analyze_fifo(results_root, out_dir, args.models)
        analyze_reservation(results_root, out_dir, args.models)
        analyze_priority_starvation(results_root, out_dir, args.models)
        analyze_gpu_idle(results_root, out_dir, args.models)
        analyze_preemptions(results_root, out_dir, args.models, args.variant)
    else:
        raise SystemExit(f"Unknown command: {args.cmd}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
